spring:
  application:
    name: notificacao
  mail:
    host: smtp.gmail.com
    port: 587
    username:
    password:
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
  thymeleaf:
    enabled: true

envio:
  email:
    remetente: eliton.albinotestes@gmail.com
    nomeRemetente: Sistema Agendador - Eliton

server:
  port: 8082

logging:
  level:
    com.javanauta.notificacao: INFO